blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView
)
from . import views

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('new/', PostCreateView.as_view(), name='post-create'),
    path('<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.about, name='blog-about'),
]

categories/urls.py
from django.urls import path
#following line is for the function based view
from . import views
#following line is for the class based view
from .views import (    CategoryList, 
                        CompanyList, 
                        CompanyCreateView, 
                        CompanyDetailView, 
                        CompanyUpdateView,
                        CompanyDeleteView,
                        AboutView,
                        AboutUsView
                      
)
from django_filters.views import FilterView
from .filters import CompanyFilter

urlpatterns = [
    #the following path is for the test only
    # path('', views.home, name = 'home'),
    path('', CategoryList.as_view(), name = 'category_list'),
    path('company/create/', CompanyCreateView.as_view(), name = 'company_create'),
    #categories/bank/1
    path('<str:category>/<int:pk>/', CompanyDetailView.as_view(), name = 'company_detail'),
    #categories/bank/1/delete
    path('<str:category>/<int:pk>/delete/', CompanyDeleteView.as_view(), name = 'company_delete'),
    #categories/bank/1/update
    path('<str:category>/<int:pk>/update/', CompanyUpdateView.as_view(), name = 'company_update'),
    path('search/', FilterView.as_view(filterset_class=CompanyFilter, 
        template_name ='categories/company_search.html'), name='search'),
    path('about/', AboutView.as_view(), name = 'aboutknowhere'),
    path('aboutus/', AboutUsView.as_view(), name = 'aboutus'),
    # why should be this \
    # because create is taken as the string value for the category
  
    #categories/bank or categories/school
    path('<str:category>/', views.CompanyList.as_view(), name='company_list'),
    
    
]

knowhere/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('categories/', include('categories.urls')),
    path('comments/', include('django_comments.urls')),
    path('products/', include('blog.urls')),
    path('chat/',include('postman.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postman/postman/urls.py
"""
If the default usage of the views suits you, simply use a line like
this one in your root URLconf to set up the default URLs::

    (r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),

Otherwise you may customize the behavior by passing extra parameters.

Recipients Max
--------------
Views supporting the parameter are: ``WriteView``, ``ReplyView``.
Example::
    ...View.as_view(max=3), name='write'),
See also the ``POSTMAN_DISALLOW_MULTIRECIPIENTS`` setting

User filter
-----------
Views supporting a user filter are: ``WriteView``, ``ReplyView``.
Example::
    def my_user_filter(user):
        if user.get_profile().is_absent:
            return "is away"
        return None
    ...
    ...View.as_view(user_filter=my_user_filter), name='write'),

function interface:
In: a User instance
Out: None, False, '', 'a reason', or ValidationError

Exchange filter
---------------
Views supporting an exchange filter are: ``WriteView``, ``ReplyView``.
Example::
    def my_exchange_filter(sender, recipient, recipients_list):
        if recipient.relationships.exists(sender, RelationshipStatus.objects.blocking()):
            return "has blacklisted you"
        return None
    ...
    ...View.as_view(exchange_filter=my_exchange_filter), name='write'),

function interface:
In:
    ``sender``: a User instance
    ``recipient``: a User instance
    ``recipients_list``: the full list of recipients or None
Out: None, False, '', 'a reason', or ValidationError

Auto-complete field
-------------------
Views supporting an auto-complete parameter are: ``WriteView``, ``ReplyView``.
Examples::
    ...View.as_view(autocomplete_channels=(None,'anonymous_ac')), name='write'),
    ...View.as_view(autocomplete_channels='write_ac'), name='write'),
    ...View.as_view(autocomplete_channel='reply_ac'), name='reply'),

Auto moderators
---------------
Views supporting an ``auto-moderators`` parameter are: ``WriteView``, ``ReplyView``.
Example::
    def mod1(message):
        # ...
        return None
    def mod2(message):
        # ...
        return None
    mod2.default_reason = 'mod2 default reason'
    ...
    ...View.as_view(auto_moderators=(mod1, mod2)), name='write'),
    ...View.as_view(auto_moderators=mod1), name='reply'),

function interface:
In: ``message``: a Message instance
Out: rating or (rating, "reason")
    with reting: None, 0 or False, 100 or True, 1..99

Others
------
Refer to documentation.
    ...View.as_view(form_classes=(MyCustomWriteForm, MyCustomAnonymousWriteForm)), name='write'),
    ...View.as_view(form_class=MyCustomFullReplyForm), name='reply'),
    ...View.as_view(form_class=MyCustomQuickReplyForm), name='view'),
    ...View.as_view(template_name='my_custom_view.html'), name='view'),
    ...View.as_view(success_url='postman:inbox'), name='reply'),
    ...View.as_view(formatters=(format_subject, format_body)), name='reply'),
    ...View.as_view(formatters=(format_subject, format_body)), name='view'),

"""
from __future__ import unicode_literals

from django import VERSION
from django.conf import settings
from django.conf.urls import url
if VERSION < (1, 10):
    from django.core.urlresolvers import reverse_lazy
else:
    from django.urls import reverse_lazy
if getattr(settings, 'POSTMAN_I18N_URLS', False):
    from django.utils.translation import pgettext_lazy
else:
    def pgettext_lazy(c, m): return m
from django.views.generic.base import RedirectView

from .views import (InboxView, SentView, ArchivesView, TrashView,
        WriteView, ReplyView, MessageView, ConversationView,
        ArchiveView, DeleteView, UndeleteView, MarkReadView, MarkUnreadView)

app_name = 'postman'
urlpatterns = [
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^inbox/(?:(?P<option>m)/)?$'), InboxView.as_view(), name='inbox'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^sent/(?:(?P<option>m)/)?$'), SentView.as_view(), name='sent'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^archives/(?:(?P<option>m)/)?$'), ArchivesView.as_view(), name='archives'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^trash/(?:(?P<option>m)/)?$'), TrashView.as_view(), name='trash'),
    url(pgettext_lazy('postman_url', r'^write/(?:(?P<recipients>[^/#]+)/)?$'), WriteView.as_view(), name='write'),
    url(pgettext_lazy('postman_url', r'^reply/(?P<message_id>[\d]+)/$'), ReplyView.as_view(), name='reply'),
    url(pgettext_lazy('postman_url', r'^view/(?P<message_id>[\d]+)/$'), MessageView.as_view(), name='view'),
    # Translators: 't' stands for 'thread'
    url(pgettext_lazy('postman_url', r'^view/t/(?P<thread_id>[\d]+)/$'), ConversationView.as_view(), name='view_conversation'),
    url(pgettext_lazy('postman_url', r'^archive/$'), ArchiveView.as_view(), name='archive'),
    url(pgettext_lazy('postman_url', r'^delete/$'), DeleteView.as_view(), name='delete'),
    url(pgettext_lazy('postman_url', r'^undelete/$'), UndeleteView.as_view(), name='undelete'),
    url(pgettext_lazy('postman_url', r'^mark-read/$'), MarkReadView.as_view(), name='mark-read'),
    url(pgettext_lazy('postman_url', r'^mark-unread/$'), MarkUnreadView.as_view(), name='mark-unread'),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('postman:inbox'), permanent=True)),
]

categories/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from requests import get
import geoip2.database
from math import sin, cos, sqrt, atan2, radians
from geopy.geocoders import Nominatim
from phonenumber_field.modelfields import PhoneNumberField
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length = 50)
    description = models.TextField()
    image = models.ImageField(upload_to='category_gallery')
    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "categories"

class Company(models.Model):
    name = models.CharField(max_length = 50)
    description = models.TextField()
    latitude = models.FloatField()
    longitude = models.FloatField()
    owner = models.ForeignKey(User, on_delete = models.CASCADE, related_name = "company_owner")
    category = models.ForeignKey(Category, on_delete = models.CASCADE)
    image = models.ImageField(upload_to='company_gallery')
    opening_hr = models.TimeField(default = '9:00')
    closing_hr = models.TimeField(default = '4:00')
    email = models.EmailField()
    #contact = models.PhoneNumberField()

    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "Companies"

    def get_absolute_url(self):
        return reverse('category_list')
		#if want to redirect to its detail page then
        # return reverse('company_detail' ,kwargs = {'pk' : self.pk})

    def get_distance(self):
        ip = get('https://api.ipify.org').text
        reader = geoip2.database.Reader('categories/GeoLite2-City.mmdb')
        response = reader.city(ip)
        current_lat = response.location.latitude
        current_lon = response.location.longitude
        comp_lat = self.latitude
        comp_lon = self.longitude
        R = 6373.0

        lat1 = radians(current_lat)
        lon1 = radians(current_lon)
        lat2 = radians(comp_lat)
        lon2 = radians(comp_lon)

        dlon = lon2 - lon1
        dlat = lat2 - lat1

        a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
        c = 2 * atan2(sqrt(a), sqrt(1 - a))

        distance = R * c* 1000
        return(distance)
    
    def get_city(self):
        
        geolocator = Nominatim(user_agent="specify_your_app_name_here")
        comp_lat = self.latitude
        comp_lon = self.longitude
        location = geolocator.reverse("" + str(comp_lat) + ","+ str(comp_lon) + "")
        city = location.address
        return(city)


class Comment(models.Model):
    text = models.TextField(max_length = 4000)
    company = models.ForeignKey(Company, on_delete= models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

categories/forms.py
from django import forms
from .models import Category, Comment

# class CompanyModelForm(forms.ModelForm):
# 	class Meta:
# 		model  = Category
# 		fields = ['name', 'description', 'category']

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['text',]

categories/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Company
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView, TemplateView
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from . forms import CommentForm
from django.views.generic.edit import FormMixin
# Create your views here.
def home(request):
    return HttpResponse("<H1> Hello welcome to my page </H1>")

class CategoryList(ListView):
    model = Category
    context_object_name = 'companies'
    template_name = 'categories/category_list'
    paginate_by = 3

class CompanyList(ListView):
    model = Company
    context_object_name = 'companies'
    template_name = 'categories/company_list.html'

    def get_queryset(self):
        category = get_object_or_404(Category, name = self.kwargs.get('category'))
        return Company.objects.filter(category = category)

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context["category"] = self.category
    #     return context
        
class CompanyCreateView(LoginRequiredMixin, CreateView):
    model = Company
    template_name = 'categories/company_create.html'
    fields = ['name', 'description', 'latitude', 'longitude', 'category']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class CompanyUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Company
    template_name = 'categories/company_update.html'
    fields = ['name', 'description']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def test_func(self):
        company = self.get_object()
        if self.request.user == company.owner:
            return True
        return False


class CompanyDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Company
    template_name = 'categories/company_delete.html'
    success_url = '/categories'
    def test_func(self):
    	company = self.get_object()
    	if self.request.user == company.owner:
    		return True
    	return False



class CompanyDetailView(DetailView):
    model = Company
    template_name = 'categories/company_detail.html'



def search(request):
    company_list = Company.objects.all()
    company_filter = CompanyFilter(request.GET, queryset=company_list)
    return render(request, 'categories/category_list.html', {'filter': company_filter})


class AboutView(TemplateView):
    template_name = 'categories/aboutknowhere.html'

class AboutUsView(TemplateView):
    template_name = 'categories/aboutus.html' 

categories/templates/categories/aboutknowhere.html
{% extends 'categories/base.html' %}
{% block content %}

<style>

  .thumbnail {
    position: relative;
	}

	.caption {
	    position: absolute;
	    top: 23%;
	    left: 15%;
	    margin:auto;
        width:70%;        
	}
    .caption .content{
        color:	#2F4F4F;
        background:#EEEEEF;
        padding-top: 70px;
        padding-bottom:70px; 
    }
    .topcaption{
        position: absolute;
	    top: 2%;
	    left: 12%;
	    width: 65%;
        text-align:left;
        color:white;
    }	

    /*for parallex scrolling*/
    .parallax {
      /* The image used */
      background-image: url("/static/step1.jpg");
      margin-top: 100px;
      position: relative;
      /* Set a specific height */
      margin-left: -20px;
      margin-right: -15px;
      margin-bottom: -25px;
      min-height: 500px; 

      /* Create the parallax scrolling effect */
      background-attachment: fixed;
      background-repeat: no-repeat;
      background-size: cover;
    /*end of parallex scrolling*/
        }
    .parallax-content{
       color: #E6E4E4;
        font-size:36px;
        text-align: center;
        padding: 50px;
    }
</style>

<div class="row" id="box-search">
    <div class="thumbnail text-center">
        <img src="/static/download copy.jpg" width="100%" height="60%" alt="My image" class="img-responsive">
        <div class="topcaption">
            <br>
            <h1>Knowhere</h1>
            <p>A place to find what you want</p>
        </div>
        <div class="caption">
                <img src="/static/back copy.png" width="100%" height="50%" alt="My image" class="img-responsive">
                <div class="content">
                    <h3>Directs you to your search.</h3>
                    <p>You can search for any company or product you want.<br>Lists the best options near you.</p>

                    

                </div>
        </div>
    </div>
</div>

<br><br><br>

<div class="container">
    <div class="row">
        <div class="col-md-3 col-sm-3 col-xs-6 linebreak" style="padding-left: 50px;"> 
            <img src="/static/search.png" width="200px">
        </div>
        <div class="col-md-3 col-sm-3 col-xs-6 linebreak">
            <img src="/static/chat.png" width="200px" height="80%">
        </div>
        <div class="col-md-3 col-sm-3 col-xs-6 linebreak">
            <img src="/static/location.png" width="200px" height="90%">
        </div>
        <div class="col-md-3 col-sm-3 col-xs-6 linebreak">
            <img src="/static/company.png" width="200px">
        </div>
    </div>
    <div class="row" style="align-items: center;">
        <div class="col-md-3 col-sm-3 col-xs-6 linebreak" style="padding-left: 50px;"> 
            A place to <b>Search</b> any product or service
        </div>
        <div class="col-md-3 col-sm-3 col-xs-6 linebreak" style="padding-left: 20px;">
            Chat with the Company Owner 
        </div>
        <div class="col-md-3 col-sm-3 col-xs-6 linebreak">
            Shows <b>location</b> of Company on <b>Map</b>
        </div>
        <div class="col-md-3 col-sm-3 col-xs-6 linebreak">
            Create Company Account
        </div>
    </div>
</div>







<div class="parallax" style="height: 50px;">
<div class="parallax-content">
    <br>
    <h1>BRIDGE BETWEEN COMPANY AND CUSTOMER</h1>
    <br> Has the best options for you 
    <br>Create Account and explore Knowhere
</div>
</div>



{% endblock %}

categories/templates/categories/aboutus.html
{% extends 'categories/base.html' %}
{% block content %}

<style>

	.aboutus{
		margin-left: -15px;
		margin-right: -15px;
		padding: 100px;
		margin-top: 0px;
		margin-bottom:-23px;
		text-align: center;
		background-color: #DCDCDC;
		padding-bottom: 200px;
	}

    /*for parallex scrolling*/
    .parallax {
      /* The image used */
      background-image: url("/static/step1.jpg");
      position: relative;
      
      /* Set a specific height */
      margin-left: -20px;
      margin-right: -15px;
      margin-bottom: 0px;
      min-height: 500px; 

      /* Create the parallax scrolling effect */
      background-attachment: fixed;
      background-repeat: no-repeat;
      background-size: cover;
    /*end of parallex scrolling*/
        }
    .parallax-content{
       color: #E6E4E4;
        font-size:36px;
        text-align: center;
        top: 0;
        padding: 50px;
    }
</style>
<div class="parallax" style="height: 50px;">
	<div class="parallax-content">
		<br>
	    <h1>BRIDGE BETWEEN COMPANY AND CUSTOMER</h1>
	    <br><br>
	    <h3>A greatful experiece with Knowhere</h3>
	</div>
</div>

<div class="aboutus">
		<h1>About Us</h1><br><br>

		<div class="container">
    <div class="row">
        <div class="col-md-3 col-sm-3 col-xs-6 linebreak"> 
            <img src="/static/suku.png" width="250px">
        </div>
        <div class="col-md-3 col-sm-3 col-xs-6 linebreak">
            <img src="/static/progress.png" width="250px">
        </div>
        <div class="col-md-3 col-sm-3 col-xs-6 linebreak">
            <img src="/static/anjelika.png" width="250px">
        </div>
        <div class="col-md-3 col-sm-3 col-xs-6 linebreak">
            <img src="/static/prakash.png" width="250px">
        </div>
    </div>
    <div class="row" style="align-items: center;">
        <div class="col-md-3 col-sm-3 col-xs-6 linebreak" style="padding-left: 20px;"> 
            <b>Sandesh Sukubhattu</b>
            <br>Student of Kathmandu University
            <br>From Bhaktapur
            <br>Contact no:9818330630
        </div>
        <div class="col-md-3 col-sm-3 col-xs-6 linebreak" style="padding-left: 20px;">
            <b>Progress Sharma</b>
            <br>Student of Kathmandu University
            <br>From Gorkha
            <br>Contact no:9846491233
        </div>
        <div class="col-md-3 col-sm-3 col-xs-6 linebreak" style="padding-left:20px;">
            <b>Anjelika Sah</b>
            <br>Student of Kathmandu University
            <br>From Janakpur
            <br>Contact no:9843398861
        </div>
        <div class="col-md-3 col-sm-3 col-xs-6 linebreak">
            <b>Prakash Khatri</b>
            <br>Student of Kathmandu University
            <br>From Nepalgunj
            <br>Contact no:9840711858
        </div>
    </div>
</div>
</div>




{% endblock %}

categories/templates/categories/company_create.html
{% extends 'categories/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<div class = "container" style="margin-left:250px; padding-right:350px;">
	    <form method = 'POST'>
				<h1><center>Create Your Company</center></h1>

	        {% csrf_token %}
	        {{form|crispy}}
	        <button type = "submit" value = "submit" class="btn btn-dark"> Create </button>
	    </form>
	</div>
	
	 <b> Click on the map to get your latitude and longitude . Copy the latitude and longitude in your above form for company.</b>

	<style>
		#mapid { height: 500px; }
	</style>

	 <div id="mapid"></div>

	<script>
		var mymap = L.map('mapid').setView([27.624979, 85.541210], 13);
		L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
    		attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
    		maxZoom: 18,
    		id: 'mapbox.streets',
    		accessToken: 'your.mapbox.access.token'
		}).addTo(mymap);
		var popup = L.popup();

		function onMapClick(e) {
    		popup
    	    	.setLatLng(e.latlng)
        		.setContent("You clicked the map at " + e.latlng.toString()+"Is this your location? ")
        		.openOn(mymap);
}

mymap.on('click', onMapClick);
	</script>
{% endblock %}

categories/templates/categories/company_delete.html
{% extends 'categories/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<form method = 'POST'>
    	{% csrf_token %}
    	{{form|crispy}}
    	Do you want to delete {{object.name}}
    	<button type = "submit" class="btn btn-link"> Delete </button>
	</form>
{% endblock %}

categories/templates/categories/company_detail.html
{% extends 'categories/base.html' %}
{% load crispy_forms_tags %}
{% load comments %}
{% block content %}
<h1>if you are owner you can update or delete this </h1>
<a href ="{% url 'company_update' company.category company.id %}"><button>update</button></a>
<a href = "{% url 'company_delete' company.category company.id %}"><button>delete</button></a>
<center><h3>{{object.name}}</h3></center>
		<style>

			 html,body{
				height: 90%;
				width: 100%;
				margin:auto;
			}
			#map {
				height:90%;
				width:50%;
				margin:auto;
			}
		</style>


	<div id="map" class="map"></div>
		<script>
		//var map = L.map('map').fitWorld();
			var map = L.map('map').setView([{{object.latitude}}, {{object.longitude }}], 11);
			L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
			maxZoom: 18,
			attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
			'<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
			'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
			id: 'mapbox.streets'
			}).addTo(map);
			function onLocationFound(e)
			{
				L.marker(e.latlng).addTo(map);
				showOnScreen(e.latlng.lat, e.latlng.lng);
				calculateDistance(e.latlng);
			}
			map.on('locationfound', onLocationFound);
			map.locate({ maxZoom: 16});
			function showOnScreen(long, lat)
			{
				document.getElementById('desc').innerHTML = long + ","+ lat;
			}
			function calculateDistance(e)
			{
				distr = e.distanceTo(L.latLng({{object.latitude}},{{object.longitude}}));
				document.getElementById('distr').innerHTML = distr;
			}
			var myIcon = L.icon(
				{
					iconUrl: 'https://image.flaticon.com/icons/svg/484/484167.svg',
					iconSize: [38, 95],
					iconAnchor: [22, 94],
					popupAnchor: [-3, -76],
					shadowUrl: '',
					shadowSize: [68, 95],
					shadowAnchor: [22, 94]
				});
			L.marker([{{object.latitude}}, {{object.longitude}}], {icon:myIcon}).addTo(map)
		.bindPopup("{{object.name}}").openPopup();


			map.on('click', function(e)
			{
				alert("Lat, Lon : " + e.latlng.lat + ", " + e.latlng.lng);
			});
			map.on('click', function(e)
			{
				var popLocation= e.latlng;
				var popup = L.popup()
				.setLatLng(popLocation)
				.setContent('you clicked here')
				.openOn(map);
			});
		</script>
	<div>
	{% comment %} <div id='distr' style="margin-left:200px;"></div>
	<div id='desc' style="margin-left:200px;"></div> {% endcomment %}

	</div>

	<div style="margin-left:200px;">


<button class="btn btn-dark"style="margin-left:200px;;">
	<a href="{% url 'postman:write' object.owner %}" style="color:white;">write to {{ object.owner }}
	</a>
</button>
 <br>

 <b> Address: {{object.get_city }}</b><br>
<b> you are {{ object.get_distance }} metres away from " {{ object.name }} ". See the blue marker for your own location </b>
 {% get_comment_count for categories.company object.pk as comment_count %}
<p>{{ comment_count }} comments have been posted about this place .</p>



{% get_comment_list for categories.company object.pk as comment_list %}
{% for comment in comment_list %}
<p>Posted by: {{ comment.user_name }} on {{ comment.submit_date }}</p>
...
<p>Comment: {{ comment.comment }}</p>
...
{% endfor %}

{% comment %} {% render_comment_form for company %} {% endcomment %}


{% if user.is_authenticated %}
    {% get_comment_form for company as form %}
    <form action="{% comment_form_target %}" method="POST">
    {% csrf_token %}
    {{ form.comment }}

    {{ form.content_type }}
    {{ form.object_pk }}
    {{ form.timestamp }}
    {{ form.security_hash }}

    <input type="hidden" name="next" value="{% url 'company_detail' object.category object.pk %}" />

    <input type="hidden" name="next" value="{% url 'aboutus' %}" />

    <input type="submit" value="Add comment" id="id_submit" />
    </form>
{% else %}
    <p>Please <a href="{% url 'login' %}">log in</a> to leave a comment.</p>
{% endif %}
{% endblock %}

categories/templates/categories/company_list.html
{% extends 'categories/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<br><br>
	<div class = "container">
		<a href = "{% url 'company_create' %}"><button class="btn btn-success" >Add a new new company</button></a>
	</div>
	{% for company in companies %}

		<style>
		a{
			color: #464848;
			text-align:left;
		}
		a:hover{
			color: #676969;
			text-decoration: none;
		}
		tr{
			background:#E8EAE9;
			border-radius: 25px;
		}
		table{
			width:100%;
		}
		td:first-child {
			border-top-left-radius: 10px;
			border-bottom-left-radius: 10px;
			padding:20px;
		}
		td:last-child {
				border-bottom-right-radius: 10px;
				border-top-right-radius: 10px;
				padding:20px;
		}
	</style>
	<br>

	<div class="container">
			<a href="{% url 'company_detail'  company.category company.id %}">
				<table>
						<tr>
							<td width="250">
								<h3>{{company.name}}</h3>
							</td>
							<td>
								<b>Discription:</b><br> {{company.description}}<br>
								<b>Owner: </b><br>{{company.owner}}<br>
								<b>Distance from you: </b>{{ company.get_distance}} m <br>
								<b>Address: </b>{{company.get_city}}<br>
							</td>
						</tr>
				</table>
			</a>
		<hr>
	</div>

	
	{% endfor %}
{% endblock %}